packages:
  - packages/*
  - apps/*
  - '!**/test/**'

ignoredBuiltDependencies:
  - '@seorii/win32-displayconfig'
  - electron-acrylic-window
  - electron-winstaller

onlyBuiltDependencies:
  - '@seorii/win32-displayconfig'
  - electron
  - electron-acrylic-window
  - electron-winstaller
  - vue-demi
