/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/ui/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./src/components/ui/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./src/components/ui/avatar/AvatarImage.vue')['default']
    Bubble: typeof import('./src/components/ui/bubble/Bubble.vue')['default']
    BubbleContent: typeof import('./src/components/ui/bubble/BubbleContent.vue')['default']
    BubbleGroup: typeof import('./src/components/ui/bubble/BubbleGroup.vue')['default']
    BubbleReactions: typeof import('./src/components/ui/bubble/BubbleReactions.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    copy: typeof import('./src/components/left copy/index.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Left: typeof import('./src/components/left/index.vue')['default']
    Message: typeof import('./src/components/ui/message/Message.vue')['default']
    MessageAvatar: typeof import('./src/components/ui/message/MessageAvatar.vue')['default']
    MessageContent: typeof import('./src/components/ui/message/MessageContent.vue')['default']
    MessageFooter: typeof import('./src/components/ui/message/MessageFooter.vue')['default']
    MessageGroup: typeof import('./src/components/ui/message/MessageGroup.vue')['default']
    MessageHeader: typeof import('./src/components/ui/message/MessageHeader.vue')['default']
    MessageScroller: typeof import('./src/components/ui/message-scroller/MessageScroller.vue')['default']
    MessageScrollerButton: typeof import('./src/components/ui/message-scroller/MessageScrollerButton.vue')['default']
    MessageScrollerContent: typeof import('./src/components/ui/message-scroller/MessageScrollerContent.vue')['default']
    MessageScrollerItem: typeof import('./src/components/ui/message-scroller/MessageScrollerItem.vue')['default']
    MessageScrollerProvider: typeof import('./src/components/ui/message-scroller/MessageScrollerProvider.vue')['default']
    MessageScrollerViewport: typeof import('./src/components/ui/message-scroller/MessageScrollerViewport.vue')['default']
    Middle: typeof import('./src/components/middle/index.vue')['default']
    ResizableHandle: typeof import('./src/components/ui/resizable/ResizableHandle.vue')['default']
    ResizablePanelGroup: typeof import('./src/components/ui/resizable/ResizablePanelGroup.vue')['default']
    Right: typeof import('./src/components/right/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Top: typeof import('./src/components/top/index.vue')['default']
  }
}
