/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/ui/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./src/components/ui/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./src/components/ui/avatar/AvatarImage.vue')['default']
    Bubble: typeof import('./src/components/ui/bubble/Bubble.vue')['default']
    BubbleContent: typeof import('./src/components/ui/bubble/BubbleContent.vue')['default']
    BubbleGroup: typeof import('./src/components/ui/bubble/BubbleGroup.vue')['default']
    BubbleReactions: typeof import('./src/components/ui/bubble/BubbleReactions.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    DropdownMenu: typeof import('./src/components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./src/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./src/components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./src/components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./src/components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./src/components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./src/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./src/components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./src/components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./src/components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    Hover: typeof import('./src/components/hover/index.vue')['default']
    HoverCard: typeof import('./src/components/hover-card/index.vue')['default']
    HoverCardContent: typeof import('reka-ui')['HoverCardContent']
    HoverCardPortal: typeof import('reka-ui')['HoverCardPortal']
    HoverCardRoot: typeof import('reka-ui')['HoverCardRoot']
    HoverCardTrigger: typeof import('reka-ui')['HoverCardTrigger']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    InputGroup: typeof import('./src/components/ui/input-group/InputGroup.vue')['default']
    InputGroupAddon: typeof import('./src/components/ui/input-group/InputGroupAddon.vue')['default']
    InputGroupButton: typeof import('./src/components/ui/input-group/InputGroupButton.vue')['default']
    InputGroupInput: typeof import('./src/components/ui/input-group/InputGroupInput.vue')['default']
    InputGroupText: typeof import('./src/components/ui/input-group/InputGroupText.vue')['default']
    InputGroupTextarea: typeof import('./src/components/ui/input-group/InputGroupTextarea.vue')['default']
    Message: typeof import('./src/components/ui/message/Message.vue')['default']
    MessageAvatar: typeof import('./src/components/ui/message/MessageAvatar.vue')['default']
    MessageContent: typeof import('./src/components/ui/message/MessageContent.vue')['default']
    MessageFooter: typeof import('./src/components/ui/message/MessageFooter.vue')['default']
    MessageGroup: typeof import('./src/components/ui/message/MessageGroup.vue')['default']
    MessageHeader: typeof import('./src/components/ui/message/MessageHeader.vue')['default']
    MessageScroller: typeof import('./src/components/ui/message-scroller/MessageScroller.vue')['default']
    MessageScrollerButton: typeof import('./src/components/ui/message-scroller/MessageScrollerButton.vue')['default']
    MessageScrollerContent: typeof import('./src/components/ui/message-scroller/MessageScrollerContent.vue')['default']
    MessageScrollerItem: typeof import('./src/components/ui/message-scroller/MessageScrollerItem.vue')['default']
    MessageScrollerProvider: typeof import('./src/components/ui/message-scroller/MessageScrollerProvider.vue')['default']
    MessageScrollerViewport: typeof import('./src/components/ui/message-scroller/MessageScrollerViewport.vue')['default']
    ResizableHandle: typeof import('./src/components/ui/resizable/ResizableHandle.vue')['default']
    ResizablePanelGroup: typeof import('./src/components/ui/resizable/ResizablePanelGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('./src/components/ui/textarea/Textarea.vue')['default']
  }
}
